# =========================================================
# Kitty
# =========================================================

# ---------------------------------------------------------
# Matugen colors
# ---------------------------------------------------------

include colors.conf


# ---------------------------------------------------------
# Transparency
# ---------------------------------------------------------

dynamic_background_opacity yes


# ---------------------------------------------------------
# Cursor
# ---------------------------------------------------------

cursor_shape block

cursor_blink_interval 0.6

cursor_trail 3
cursor_trail_decay 0.1 0.4

cursor_stop_blinking_after 0


# ---------------------------------------------------------
# Misc
# ---------------------------------------------------------
background_opacity 0.4
