[config]
# ...
[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = "pkill swaync; swaync & disown"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.qml"
output_path = "~/.config/quickshell/notch/themes/Colors.qml"

