$background = rgb(15, 20, 22)
$foreground = rgb(222, 227, 230)

$primary = rgba(133, 210, 232, 0.7)
$on_primary = rgb(0, 54, 65)

$secondary = rgba(178, 203, 211, 0.7)
$on_secondary = rgb(29, 52, 58)

$tertiary = rgba(191, 196, 235, 0.7)
$on_tertiary = rgb(41, 46, 77)

$error = rgba(255, 180, 171, 0.7)
$on_error = rgb(105, 0, 5)

$surface = rgba(15, 20, 22, 0.55)
$on_surface = rgb(222, 227, 230)

$surface_variant = rgba(63, 72, 75, 0.55)
$on_surface_variant = rgb(191, 200, 203)

$outline = rgba(137, 146, 149, 0.7)
$outline_variant = rgba(63, 72, 75, 0.7)
