$background = rgb({{background.default.red}}, {{background.default.green}}, {{background.default.blue}})
$foreground = rgb({{on_background.default.red}}, {{on_background.default.green}}, {{on_background.default.blue}})

$primary = rgba({{primary.default.red}}, {{primary.default.green}}, {{primary.default.blue}}, 0.7)
$on_primary = rgb({{on_primary.default.red}}, {{on_primary.default.green}}, {{on_primary.default.blue}})

$secondary = rgba({{secondary.default.red}}, {{secondary.default.green}}, {{secondary.default.blue}}, 0.7)
$on_secondary = rgb({{on_secondary.default.red}}, {{on_secondary.default.green}}, {{on_secondary.default.blue}})

$tertiary = rgba({{tertiary.default.red}}, {{tertiary.default.green}}, {{tertiary.default.blue}}, 0.7)
$on_tertiary = rgb({{on_tertiary.default.red}}, {{on_tertiary.default.green}}, {{on_tertiary.default.blue}})

$error = rgba({{error.default.red}}, {{error.default.green}}, {{error.default.blue}}, 0.7)
$on_error = rgb({{on_error.default.red}}, {{on_error.default.green}}, {{on_error.default.blue}})

$surface = rgba({{surface.default.red}}, {{surface.default.green}}, {{surface.default.blue}}, 0.55)
$on_surface = rgb({{on_surface.default.red}}, {{on_surface.default.green}}, {{on_surface.default.blue}})

$surface_variant = rgba({{surface_variant.default.red}}, {{surface_variant.default.green}}, {{surface_variant.default.blue}}, 0.55)
$on_surface_variant = rgb({{on_surface_variant.default.red}}, {{on_surface_variant.default.green}}, {{on_surface_variant.default.blue}})

$outline = rgba({{outline.default.red}}, {{outline.default.green}}, {{outline.default.blue}}, 0.7)
$outline_variant = rgba({{outline_variant.default.red}}, {{outline_variant.default.green}}, {{outline_variant.default.blue}}, 0.7)
