$background = {{ colors.background.default.rgb }}
$foreground = {{ colors.on_background.default.rgb }}

$primary = {{ colors.primary.default.rgba | set_alpha: 0.7 }}
$on_primary = {{ colors.on_primary.default.rgb }}

$secondary = {{ colors.secondary.default.rgba | set_alpha: 0.7 }}
$on_secondary = {{ colors.on_secondary.default.rgb }}

$tertiary = {{ colors.tertiary.default.rgba | set_alpha: 0.7 }}
$on_tertiary = {{ colors.on_tertiary.default.rgb }}

$error = {{ colors.error.default.rgba | set_alpha: 0.7 }}
$on_error = {{ colors.on_error.default.rgb }}

$surface = {{ colors.surface.default.rgba | set_alpha: 0.55 }}
$on_surface = {{ colors.on_surface.default.rgb }}

$surface_variant = {{ colors.surface_variant.default.rgba | set_alpha: 0.55 }}
$on_surface_variant = {{ colors.on_surface_variant.default.rgb }}

$outline = {{ colors.outline.default.rgba | set_alpha: 0.7 }}
$outline_variant = {{ colors.outline_variant.default.rgba | set_alpha: 0.7 }}
